name: Run R script and commit changes

on: workflow_dispatch
 # schedule:
 #   - cron: '0 10 * * *'  # trigger the workflow every day at 5am

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3.0  # adjust the R version as needed

    - name: Install dependencies
      run: |
        R -q -e 'install.packages(c("dplyr", "stringr", "readr", "sf", "leaflet", "htmltools"))'
      # add more dependencies if needed

    - name: Run R script
      run: Rscript scripts/leaflet-website-gen.R  # adjust the path to your R script

    - name: Commit changes
      run: |
        git config --global user.name "jcksanderson"
        git config --global user.email "jackmsanderson@gmail.com"
        git add .
        git commit -m "Update data [skip ci]"
        git push
