name: Update DB and Map

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # trigger the workflow every day at 4am

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    permissions:
     contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3.0  # adjust the R version as needed

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        packages: |
          any::dplyr
          any::stringr
          any::sf
          any::leaflet
          any::htmltools
          any::lubridate
          any::rvest
          any::tidygeocoder
          any::duckdb
          any::DBI

    - name: update database
      run: Rscript scripts/database-generation.R

    - name: update map
      run: Rscript scripts/leaflet-website-gen.R

    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Website
